# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 044438cf878e367d3e3cfa560da6528bee4827df5e4623e7f815a295957b4d98baf1656b635cc272119ee6213234b28164a0353189f09cb9ce7bb1c45c26e505

test:
  secret_key_base: 48d66442ce1cb4aa6e6a90a5ab3c68a325a7cb54a44822a2704b370111d11195ed73e11c832de7d0759fa0c0098e69794a4da547a08768d7307353ea825f573d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
